In [11]:
import zipfile
import os

zip_path = r"C:\Users\husnu\Downloads\drive-download-20260406T221849Z-3-001.zip"
extract_path = r"C:\Users\husnu\Downloads\panynj_extracted"

# klasörü oluştur
os.makedirs(extract_path, exist_ok=True)

# zip'i aç
with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

print("ZIP açıldı.")
print("Çıkarılan klasör:", extract_path)

# içindeki pdf'leri bul
pdf_files = []

for root, dirs, files in os.walk(extract_path):
    for file in files:
        if file.lower().endswith(".pdf"):
            full_path = os.path.join(root, file)
            pdf_files.append(full_path)

print(f"Bulunan PDF sayısı: {len(pdf_files)}")

for pdf in pdf_files:
    print(pdf)

ZIP açıldı.
Çıkarılan klasör: C:\Users\husnu\Downloads\panynj_extracted
Bulunan PDF sayısı: 15
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2011.pdf
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2012.pdf
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2013.pdf
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2014.pdf
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2015.pdf
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2016.pdf
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2017.pdf
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2018.pdf
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2019.pdf
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2020.pdf
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2021.pdf
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2022.pdf
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2023.pdf
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2024.pdf
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2025.pdf

In [17]:
!{sys.executable} -m pip install tabula-py

Collecting tabula-py
  Downloading tabula_py-2.10.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: pandas>=0.25.3 in c:\users\husnu\anaconda3\lib\site-packages (from tabula-py) (2.2.3)
Requirement already satisfied: numpy>1.24.4 in c:\users\husnu\anaconda3\lib\site-packages (from tabula-py) (2.1.3)
Requirement already satisfied: distro in c:\users\husnu\anaconda3\lib\site-packages (from tabula-py) (1.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\husnu\anaconda3\lib\site-packages (from pandas>=0.25.3->tabula-py) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\husnu\anaconda3\lib\site-packages (from pandas>=0.25.3->tabula-py) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\husnu\anaconda3\lib\site-packages (from pandas>=0.25.3->tabula-py) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\husnu\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=0.25.3->tabula-py) (1.17.0)
Downloading tabula_py-2.10.0-py3-none-any.whl (12.0 MB)
   ---------------------------------------- 0.0/12.0 MB ? eta -:--:--
    --------------------------------------- 0.3/12.0 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.0 MB 2.6 MB/s eta 0:00:05
   --- ------------------------------------ 1.0/12.0 MB 2.6 MB/s eta 0:00:05
   ------ --------------------------------- 1.8/12.0 MB 2.4 MB/s eta 0:00:05
   ------- -------------------------------- 2.4/12.0 MB 2.3 MB/s eta 0:00:05
   --------- ------------------------------ 2.9/12.0 MB 2.5 MB/s eta 0:00:04
   ----------- ---------------------------- 3.4/12.0 MB 2.5 MB/s eta 0:00:04
   ------------- -------------------------- 4.2/12.0 MB 2.5 MB/s eta 0:00:04
   --------------- ------------------------ 4.7/12.0 MB 2.5 MB/s eta 0:00:03
   ----------------- ---------------------- 5.2/12.0 MB 2.6 MB/s eta 0:00:03
   ------------------- -------------------- 5.8/12.0 MB 2.5 MB/s eta 0:00:03
   -------------------- ------------------- 6.3/12.0 MB 2.5 MB/s eta 0:00:03
   ---------------------- ----------------- 6.8/12.0 MB 2.6 MB/s eta 0:00:03
   ------------------------ --------------- 7.3/12.0 MB 2.5 MB/s eta 0:00:02
   --------------------------- ------------ 8.1/12.0 MB 2.5 MB/s eta 0:00:02
   --------------------------- ------------ 8.4/12.0 MB 2.6 MB/s eta 0:00:02
   ------------------------------ --------- 9.2/12.0 MB 2.5 MB/s eta 0:00:02
   -------------------------------- ------- 9.7/12.0 MB 2.5 MB/s eta 0:00:01
   ---------------------------------- ----- 10.2/12.0 MB 2.6 MB/s eta 0:00:01
   ----------------------------------- ---- 10.7/12.0 MB 2.5 MB/s eta 0:00:01
   ------------------------------------- -- 11.3/12.0 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------  11.8/12.0 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------- 12.0/12.0 MB 2.5 MB/s eta 0:00:00
Installing collected packages: tabula-py
Successfully installed tabula-py-2.10.0

In [24]:
import pdfplumber
import pandas as pd
print("pdfplumber OK")

pdfplumber OK

In [25]:
import zipfile
import os

zip_path = r"C:\Users\husnu\Downloads\drive-download-20260406T221849Z-3-001.zip"
extract_path = r"C:\Users\husnu\Downloads\panynj_extracted"

os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

pdf_files = []
for root, dirs, files in os.walk(extract_path):
    for file in files:
        if file.lower().endswith(".pdf"):
            pdf_files.append(os.path.join(root, file))

pdf_files = sorted(pdf_files)

print("PDF sayısı:", len(pdf_files))
for pdf in pdf_files[:16]:
    print(pdf)

PDF sayısı: 15
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2011.pdf
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2012.pdf
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2013.pdf
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2014.pdf
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2015.pdf
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2016.pdf
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2017.pdf
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2018.pdf
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2019.pdf
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2020.pdf
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2021.pdf
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2022.pdf
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2023.pdf
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2024.pdf
C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2025.pdf

In [26]:
import pdfplumber
import os

test_pdf = pdf_files[0]
print("Test PDF:", test_pdf)

with pdfplumber.open(test_pdf) as pdf:
    print("Sayfa sayısı:", len(pdf.pages))
    first_page = pdf.pages[0]
    text = first_page.extract_text()
    print(text[:3000] if text else "Metin çıkarılamadı")

Test PDF: C:\Users\husnu\Downloads\panynj_extracted\traffic-e-zpass-usage-2011.pdf
Sayfa sayısı: 1
2011 Monthly Traffic and Percent of E-ZPass Usage
(Updated Jun/2018)
TUNNELS AND BRIDGES
(Eastbound Traffic) Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec Annual
All Crossings
Automobiles 7,943,315 7,786,178 9,115,286 9,154,369 9,613,655 9,571,519 9,917,576 9,347,570 8,985,654 9,023,450 8,844,310 9,125,590 108,428,472
Buses 235,698 225,739 268,014 264,736 274,926 275,851 277,006 275,933 259,279 257,228 247,247 248,627 3,110,284
Trucks 570,143 553,174 664,922 627,228 656,203 683,304 624,443 685,244 657,059 640,288 630,154 618,867 7,611,029
Total Vehicles 8,749,156 8,565,091 10,048,222 10,046,333 10,544,784 10,530,674 10,819,025 10,308,747 9,901,992 9,920,966 9,721,711 9,993,084 119,149,785
E-ZPass Usage (%) 76.7% 76.6% 76.9% 76.2% 76.1% 75.9% 74.3% 75.6% 77.3% 79.6% 79.7% 79.2% 77.0%
George Washington Bridge
Automobiles 3,370,936 3,272,225 3,843,661 3,895,462 4,109,595 4,087,871 4,286,338 4,029,977 3,831,941 3,794,633 3,755,512 3,838,062 46,116,213
Buses 36,807 36,337 42,201 41,868 44,575 45,933 48,498 44,918 39,980 37,018 35,205 33,718 487,058
Trucks 287,941 278,812 335,585 318,295 329,276 340,914 311,261 340,903 323,887 313,408 310,457 303,397 3,794,136
Total Vehicles 3,695,684 3,587,374 4,221,447 4,255,625 4,483,446 4,474,718 4,646,097 4,415,798 4,195,808 4,145,059 4,101,174 4,175,177 50,397,407
E-ZPass Usage (%) 74.8% 74.6% 74.9% 74.3% 74.3% 74.0% 72.3% 73.9% 75.9% 78.3% 78.5% 78.0% 75.3%
Lincoln Tunnel
Automobiles 1,244,648 1,222,260 1,435,307 1,436,851 1,469,370 1,450,951 1,446,782 1,386,454 1,368,670 1,414,449 1,360,566 1,407,683 16,643,991
Buses 165,583 156,704 185,900 183,567 187,682 186,651 184,111 186,798 179,702 181,822 176,902 180,754 2,156,176
Trucks 77,582 74,853 89,891 84,346 87,624 91,655 82,753 90,396 89,835 89,908 86,782 83,642 1,029,267
Total Vehicles 1,487,813 1,453,817 1,711,098 1,704,764 1,744,676 1,729,257 1,713,646 1,663,648 1,638,207 1,686,179 1,624,250 1,672,079 19,829,434
E-ZPass Usage (%) 79.0% 79.1% 79.1% 78.4% 78.3% 78.0% 76.3% 77.6% 79.2% 81.4% 81.6% 80.8% 79.0%
Holland Tunnel
Automobiles 1,192,262 1,183,356 1,383,611 1,354,127 1,404,464 1,392,537 1,415,311 1,333,653 1,292,859 1,337,877 1,308,279 1,369,636 15,967,972
Buses 18,936 18,580 22,661 22,175 24,059 23,971 25,336 25,690 23,379 22,350 20,367 20,700 268,204
Trucks 25,252 24,834 29,435 27,252 28,621 30,737 29,310 31,924 30,953 30,947 31,634 32,625 353,524
Total Vehicles 1,236,450 1,226,770 1,435,707 1,403,554 1,457,144 1,447,245 1,469,957 1,391,267 1,347,191 1,391,174 1,360,280 1,422,961 16,589,700
E-ZPass Usage (%) 73.8% 73.8% 74.1% 73.3% 73.1% 73.0% 71.0% 72.4% 74.3% 77.0% 77.0% 76.4% 74.1%
Goethals Bridge
Automobiles 908,233 896,210 1,044,992 1,053,866 1,128,772 1,121,666 1,206,196 1,125,589 1,076,713 1,067,176 1,053,908 1,083,376 12,766,697
Buses 8,722 8,511 10,411 10,157 10,978 11,390 11,227 11,495 9,740 9,692 8,948 8,265 119,536
Trucks 96,606 95,421 113,007 102,658 109,416 116,508 107,846 118,359 111,711 109,635 106,702 104,347 1,292,216
Total Vehicles

In [27]:
with pdfplumber.open(test_pdf) as pdf:
    for i, page in enumerate(pdf.pages[:3], start=1):
        table = page.extract_table()
        print(f"\n--- PAGE {i} ---")
        if table:
            for row in table[:10]:
                print(row)
        else:
            print("Tablo bulunamadı")

--- PAGE 1 ---
['2011 Monthly Traffic and Percent of E-ZPass Usage\n(Updated Jun/2018)']
['TUNNELS AND BRIDGES\n(Eastbound Traffic) Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec Annual']
['All Crossings']
['Automobiles 7,943,315 7,786,178 9,115,286 9,154,369 9,613,655 9,571,519 9,917,576 9,347,570 8,985,654 9,023,450 8,844,310 9,125,590 108,428,472\nBuses 235,698 225,739 268,014 264,736 274,926 275,851 277,006 275,933 259,279 257,228 247,247 248,627 3,110,284\nTrucks 570,143 553,174 664,922 627,228 656,203 683,304 624,443 685,244 657,059 640,288 630,154 618,867 7,611,029\nTotal Vehicles 8,749,156 8,565,091 10,048,222 10,046,333 10,544,784 10,530,674 10,819,025 10,308,747 9,901,992 9,920,966 9,721,711 9,993,084 119,149,785\nE-ZPass Usage (%) 76.7% 76.6% 76.9% 76.2% 76.1% 75.9% 74.3% 75.6% 77.3% 79.6% 79.7% 79.2% 77.0%']
['George Washington Bridge']
['Automobiles 3,370,936 3,272,225 3,843,661 3,895,462 4,109,595 4,087,871 4,286,338 4,029,977 3,831,941 3,794,633 3,755,512 3,838,062 46,116,213\nBuses 36,807 36,337 42,201 41,868 44,575 45,933 48,498 44,918 39,980 37,018 35,205 33,718 487,058\nTrucks 287,941 278,812 335,585 318,295 329,276 340,914 311,261 340,903 323,887 313,408 310,457 303,397 3,794,136\nTotal Vehicles 3,695,684 3,587,374 4,221,447 4,255,625 4,483,446 4,474,718 4,646,097 4,415,798 4,195,808 4,145,059 4,101,174 4,175,177 50,397,407\nE-ZPass Usage (%) 74.8% 74.6% 74.9% 74.3% 74.3% 74.0% 72.3% 73.9% 75.9% 78.3% 78.5% 78.0% 75.3%']
['Lincoln Tunnel']
['Automobiles 1,244,648 1,222,260 1,435,307 1,436,851 1,469,370 1,450,951 1,446,782 1,386,454 1,368,670 1,414,449 1,360,566 1,407,683 16,643,991\nBuses 165,583 156,704 185,900 183,567 187,682 186,651 184,111 186,798 179,702 181,822 176,902 180,754 2,156,176\nTrucks 77,582 74,853 89,891 84,346 87,624 91,655 82,753 90,396 89,835 89,908 86,782 83,642 1,029,267\nTotal Vehicles 1,487,813 1,453,817 1,711,098 1,704,764 1,744,676 1,729,257 1,713,646 1,663,648 1,638,207 1,686,179 1,624,250 1,672,079 19,829,434\nE-ZPass Usage (%) 79.0% 79.1% 79.1% 78.4% 78.3% 78.0% 76.3% 77.6% 79.2% 81.4% 81.6% 80.8% 79.0%']
['Holland Tunnel']
['Automobiles 1,192,262 1,183,356 1,383,611 1,354,127 1,404,464 1,392,537 1,415,311 1,333,653 1,292,859 1,337,877 1,308,279 1,369,636 15,967,972\nBuses 18,936 18,580 22,661 22,175 24,059 23,971 25,336 25,690 23,379 22,350 20,367 20,700 268,204\nTrucks 25,252 24,834 29,435 27,252 28,621 30,737 29,310 31,924 30,953 30,947 31,634 32,625 353,524\nTotal Vehicles 1,236,450 1,226,770 1,435,707 1,403,554 1,457,144 1,447,245 1,469,957 1,391,267 1,347,191 1,391,174 1,360,280 1,422,961 16,589,700\nE-ZPass Usage (%) 73.8% 73.8% 74.1% 73.3% 73.1% 73.0% 71.0% 72.4% 74.3% 77.0% 77.0% 76.4% 74.1%']

In [28]:
import pandas as pd
import pdfplumber
import os
import re

all_rows = []

for pdf_path in pdf_files:
    file_name = os.path.basename(pdf_path)
    year_match = re.search(r"(20\d{2}|201\d)", file_name)
    source_year = year_match.group(1) if year_match else None

    print("İşleniyor:", file_name)

    try:
        with pdfplumber.open(pdf_path) as pdf:
            for page_num, page in enumerate(pdf.pages, start=1):
                tables = page.extract_tables()

                if not tables:
                    continue

                for table_no, table in enumerate(tables, start=1):
                    for row_no, row in enumerate(table, start=1):
                        all_rows.append({
                            "source_file": file_name,
                            "source_year": source_year,
                            "page": page_num,
                            "table_no": table_no,
                            "row_no": row_no,
                            "row_data": row
                        })

    except Exception as e:
        print("HATA:", file_name, "->", e)

df_raw = pd.DataFrame(all_rows)
print(df_raw.shape)
df_raw.head()

İşleniyor: traffic-e-zpass-usage-2011.pdf
İşleniyor: traffic-e-zpass-usage-2012.pdf
İşleniyor: traffic-e-zpass-usage-2013.pdf
İşleniyor: traffic-e-zpass-usage-2014.pdf
İşleniyor: traffic-e-zpass-usage-2015.pdf
İşleniyor: traffic-e-zpass-usage-2016.pdf
İşleniyor: traffic-e-zpass-usage-2017.pdf
İşleniyor: traffic-e-zpass-usage-2018.pdf
İşleniyor: traffic-e-zpass-usage-2019.pdf
İşleniyor: traffic-e-zpass-usage-2020.pdf
İşleniyor: traffic-e-zpass-usage-2021.pdf
İşleniyor: traffic-e-zpass-usage-2022.pdf
İşleniyor: traffic-e-zpass-usage-2023.pdf
İşleniyor: traffic-e-zpass-usage-2024.pdf
İşleniyor: traffic-e-zpass-usage-2025.pdf
(303, 6)

,source_file,source_year,page,table_no,row_no,row_data
0,traffic-e-zpass-usage-2011.pdf,2011,1,1,1,[2011 Monthly Traffic and Percent of E-ZPass U...
1,traffic-e-zpass-usage-2011.pdf,2011,1,1,2,[TUNNELS AND BRIDGES\n(Eastbound Traffic) Jan ...
2,traffic-e-zpass-usage-2011.pdf,2011,1,1,3,[All Crossings]
3,traffic-e-zpass-usage-2011.pdf,2011,1,1,4,"[Automobiles 7,943,315 7,786,178 9,115,286 9,1..."
4,traffic-e-zpass-usage-2011.pdf,2011,1,1,5,[George Washington Bridge]

In [29]:
output_excel = r"C:\Users\husnu\Downloads\panynj_pdf_raw.xlsx"
df_raw.to_excel(output_excel, index=False)
print("Kaydedildi:", output_excel)

Kaydedildi: C:\Users\husnu\Downloads\panynj_pdf_raw.xlsx

In [30]:
rows_expanded = pd.DataFrame(df_raw["row_data"].tolist())
df_expanded = pd.concat(
    [df_raw.drop(columns=["row_data"]).reset_index(drop=True), rows_expanded],
    axis=1
)

print(df_expanded.shape)
df_expanded.head(20)

(303, 6)

,source_file,source_year,page,table_no,row_no,0
0,traffic-e-zpass-usage-2011.pdf,2011,1,1,1,2011 Monthly Traffic and Percent of E-ZPass Us...
1,traffic-e-zpass-usage-2011.pdf,2011,1,1,2,TUNNELS AND BRIDGES\n(Eastbound Traffic) Jan F...
2,traffic-e-zpass-usage-2011.pdf,2011,1,1,3,All Crossings
3,traffic-e-zpass-usage-2011.pdf,2011,1,1,4,"Automobiles 7,943,315 7,786,178 9,115,286 9,15..."
4,traffic-e-zpass-usage-2011.pdf,2011,1,1,5,George Washington Bridge
5,traffic-e-zpass-usage-2011.pdf,2011,1,1,6,"Automobiles 3,370,936 3,272,225 3,843,661 3,89..."
6,traffic-e-zpass-usage-2011.pdf,2011,1,1,7,Lincoln Tunnel
7,traffic-e-zpass-usage-2011.pdf,2011,1,1,8,"Automobiles 1,244,648 1,222,260 1,435,307 1,43..."
8,traffic-e-zpass-usage-2011.pdf,2011,1,1,9,Holland Tunnel
9,traffic-e-zpass-usage-2011.pdf,2011,1,1,10,"Automobiles 1,192,262 1,183,356 1,383,611 1,35..."
10,traffic-e-zpass-usage-2011.pdf,2011,1,1,11,Goethals Bridge
11,traffic-e-zpass-usage-2011.pdf,2011,1,1,12,"Automobiles 908,233 896,210 1,044,992 1,053,86..."
12,traffic-e-zpass-usage-2011.pdf,2011,1,1,13,Outerbridge Crossing
13,traffic-e-zpass-usage-2011.pdf,2011,1,1,14,"Automobiles 989,714 979,631 1,134,072 1,141,72..."
14,traffic-e-zpass-usage-2011.pdf,2011,1,1,15,Bayonne Bridge
15,traffic-e-zpass-usage-2011.pdf,2011,1,1,16,"Automobiles 237,522 232,496 273,643 272,343 28..."
16,traffic-e-zpass-usage-2012.pdf,2012,1,1,1,2012 Monthly Traffic and Percent of E-ZPass Us...
17,traffic-e-zpass-usage-2012.pdf,2012,1,1,2,TUNNELS AND BRIDGES\n(Eastbound Traffic) Jan F...
18,traffic-e-zpass-usage-2012.pdf,2012,1,1,3,All Crossings
19,traffic-e-zpass-usage-2012.pdf,2012,1,1,4,"Automobiles 8,213,612 8,035,177 8,922,026 8,92..."

In [31]:
df = df_expanded.copy()

df["text"] = df[0].astype(str).str.strip()
df = df[["source_year", "text"]]

df.head()

  source_year                                               text
0        2011  2011 Monthly Traffic and Percent of E-ZPass Us...
1        2011  TUNNELS AND BRIDGES\n(Eastbound Traffic) Jan F...
2        2011                                      All Crossings
3        2011  Automobiles 7,943,315 7,786,178 9,115,286 9,15...
4        2011                           George Washington Bridge

In [32]:
facilities = [
    "George Washington Bridge",
    "Lincoln Tunnel",
    "Holland Tunnel",
    "Goethals Bridge",
    "Outerbridge Crossing",
    "Bayonne Bridge"
]

current_facility = None
parsed_rows = []

for _, row in df.iterrows():
    text = row["text"]
    year = row["source_year"]

    # facility yakala
    if text in facilities:
        current_facility = text
        continue

    # veri satırı mı?
    if "Automobiles" in text and current_facility:
        parsed_rows.append({
            "year": year,
            "facility": current_facility,
            "raw_values": text
        })

parsed_df = pd.DataFrame(parsed_rows)

parsed_df.head()

,year,facility,raw_values
0,2011,George Washington Bridge,"Automobiles 3,370,936 3,272,225 3,843,661 3,89..."
1,2011,Lincoln Tunnel,"Automobiles 1,244,648 1,222,260 1,435,307 1,43..."
2,2011,Holland Tunnel,"Automobiles 1,192,262 1,183,356 1,383,611 1,35..."
3,2011,Goethals Bridge,"Automobiles 908,233 896,210 1,044,992 1,053,86..."
4,2011,Outerbridge Crossing,"Automobiles 989,714 979,631 1,134,072 1,141,72..."

In [33]:
import re

def extract_numbers(text):
    nums = re.findall(r"\d{1,3}(?:,\d{3})+", text)
    return [int(n.replace(",", "")) for n in nums]

parsed_df["values"] = parsed_df["raw_values"].apply(extract_numbers)

parsed_df.head()

,year,facility,raw_values,values
0,2011,George Washington Bridge,"Automobiles 3,370,936 3,272,225 3,843,661 3,89...","[3370936, 3272225, 3843661, 3895462, 4109595, ..."
1,2011,Lincoln Tunnel,"Automobiles 1,244,648 1,222,260 1,435,307 1,43...","[1244648, 1222260, 1435307, 1436851, 1469370, ..."
2,2011,Holland Tunnel,"Automobiles 1,192,262 1,183,356 1,383,611 1,35...","[1192262, 1183356, 1383611, 1354127, 1404464, ..."
3,2011,Goethals Bridge,"Automobiles 908,233 896,210 1,044,992 1,053,86...","[908233, 896210, 1044992, 1053866, 1128772, 11..."
4,2011,Outerbridge Crossing,"Automobiles 989,714 979,631 1,134,072 1,141,72...","[989714, 979631, 1134072, 1141720, 1216294, 12..."

In [34]:
months = [
    "Jan","Feb","Mar","Apr","May","Jun",
    "Jul","Aug","Sep","Oct","Nov","Dec"
]

In [35]:
final_rows = []

for _, row in parsed_df.iterrows():
    year = row["year"]
    facility = row["facility"]
    values = row["values"]

    for i, val in enumerate(values):
        if i < 12:
            final_rows.append({
                "year": year,
                "facility": facility,
                "month": months[i],
                "traffic": val
            })

final_df = pd.DataFrame(final_rows)

final_df.head()

   year                  facility month  traffic
0  2011  George Washington Bridge   Jan  3370936
1  2011  George Washington Bridge   Feb  3272225
2  2011  George Washington Bridge   Mar  3843661
3  2011  George Washington Bridge   Apr  3895462
4  2011  George Washington Bridge   May  4109595

In [39]:
final_df["traffic"] = final_df["traffic"].apply(lambda x: f"{x:,}")

In [46]:
output_path = r"C:\Users\husnu\OneDrive\Desktop\interview\traffic_clean.csv"
final_df.to_csv(output_path, index=False)

print("Hazır:", output_path)

Hazır: C:\Users\husnu\OneDrive\Desktop\interview\traffic_clean.csv